language: ruby
rvm:
  # No ruby-head as it is unstable
  # No Rubinius as it requires extra setup and is not supported yet
  # No jRuby as it depends on native C extensions
  # MRI
  # - 1.9.2 # ActiveSupport now needs >= 1.9.3
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  # Setup display, used by webkit driver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Setup TRAVIS context
  - "export TRAVIS_CONTEXT=1"
