source "http://rubygems.org"

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'

# Rails itself
gem 'rails', '~> 3.2'

# Devise
gem 'devise'

group :test do

  # RSpec
  gem 'rspec'
  gem 'rspec-rails'

  # Cucumber
  gem 'cucumber-rails', :require => false
  gem 'sqlite3'
  gem 'database_cleaner'

  # Capybara-webkit
  gem 'capybara-webkit'

  # Factory girl
  gem 'factory_girl_rails'

  # CodeClimate integration
  gem 'codeclimate-test-reporter', require: nil

end
